package com.arlessas.gestion

import java.util.Locale

internal data class QuimicoCanonico(
    val documentoId: String,
    val codigoOriginal: String,
    val categoria: String,
    val subcategoria: String,
    val ubicacion: String,
    val item: String,
    val unidad: String,
    val stockInicial: Double,
    val filasExcel: List<Int> = emptyList(),
) {
    val modulo: String
        get() = ModulosInventario.moduloQuimico(categoria, ubicacion)
}

internal object QuimicosCanonicos {
    const val VERSION = "quimicos_2026_06_07_stock_g_modulos_v5"
    const val FUENTE = "Inventario_Agroquimicos.xlsx columna G Stock"

    val items: List<QuimicoCanonico> = listOf(
        QuimicoCanonico(
            documentoId = "Q-FER113-BODEGA-AZUL",
            codigoOriginal = "FER113",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "COSMOQUEL CALCIO",
            unidad = "GRAMO",
            stockInicial = 19000.0,
            filasExcel = listOf(4),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER130-BODEGA-AZUL",
            codigoOriginal = "FER130",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "COSMOQUEL HIERRO",
            unidad = "GRAMO",
            stockInicial = 49332.0,
            filasExcel = listOf(5),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER128-BODEGA-AZUL",
            codigoOriginal = "FER128",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "COSMOQUEL MANGANESO",
            unidad = "GRAMO",
            stockInicial = 72110.0,
            filasExcel = listOf(6),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER118-BODEGA-AZUL",
            codigoOriginal = "FER118",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "COSMOQUEL ZINC",
            unidad = "GRAMO",
            stockInicial = 64235.0,
            filasExcel = listOf(7),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER170-BODEGA-AZUL",
            codigoOriginal = "FER170",
            categoria = "Acondicionador",
            subcategoria = "Acondicionador de suelo",
            ubicacion = "BODEGA AZUL",
            item = "82 - HYDROSAB",
            unidad = "GRAMO",
            stockInicial = 25000.0,
            filasExcel = listOf(8),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR047-BODEGA-AZUL",
            codigoOriginal = "VAR047",
            categoria = "Regulador",
            subcategoria = "Regulador de crecimiento",
            ubicacion = "BODEGA AZUL",
            item = "IBA.3",
            unidad = "GRAMO",
            stockInicial = 4540.0,
            filasExcel = listOf(9),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER156-BODEGA-AZUL",
            codigoOriginal = "FER156",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "90 - KELATEX MAGNESIO",
            unidad = "GRAMO",
            stockInicial = 53000.0,
            filasExcel = listOf(10),
        ),
        QuimicoCanonico(
            documentoId = "Q-FUN016-BODEGA-AZUL",
            codigoOriginal = "FUN016",
            categoria = "Fungicida",
            subcategoria = "Foliar sanitario",
            ubicacion = "BODEGA AZUL",
            item = "KUMULUS WG",
            unidad = "GRAMO",
            stockInicial = 2920.0,
            filasExcel = listOf(11),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER029-BODEGA-AZUL",
            codigoOriginal = "FER029",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "MOLIB K",
            unidad = "GRAMO",
            stockInicial = 7029.0,
            filasExcel = listOf(12),
        ),
        QuimicoCanonico(
            documentoId = "Q-BIO006-BODEGA-AZUL",
            codigoOriginal = "BIO006",
            categoria = "Nematicida",
            subcategoria = "Suelo / ra\u00edces",
            ubicacion = "BODEGA AZUL",
            item = "Nemacyl",
            unidad = "GRAMO",
            stockInicial = 10000.0,
            filasExcel = listOf(13),
        ),
        QuimicoCanonico(
            documentoId = "Q-FUN005-BODEGA-AZUL",
            codigoOriginal = "FUN005",
            categoria = "Fungicida",
            subcategoria = "Foliar sanitario",
            ubicacion = "BODEGA AZUL",
            item = "98 - OXICRON 58.8% X KG",
            unidad = "GRAMO",
            stockInicial = 7575.0,
            filasExcel = listOf(14),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR048-BODEGA-AZUL",
            codigoOriginal = "VAR048",
            categoria = "Regulador",
            subcategoria = "Regulador de crecimiento",
            ubicacion = "BODEGA AZUL",
            item = "piedra Alumbre",
            unidad = "GRAMO",
            stockInicial = 6000.0,
            filasExcel = listOf(15),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR045-BODEGA-AZUL",
            codigoOriginal = "VAR045",
            categoria = "Regulador",
            subcategoria = "Regulador de crecimiento",
            ubicacion = "BODEGA AZUL",
            item = "90 - PROGIBB REGULADOR DE CRECIMEINTO",
            unidad = "GRAMO",
            stockInicial = 1000.0,
            filasExcel = listOf(16),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER116-BODEGA-AZUL",
            codigoOriginal = "FER116",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "REBROTE",
            unidad = "GRAMO",
            stockInicial = 39940.0,
            filasExcel = listOf(17),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER171-BODEGA-AZUL",
            codigoOriginal = "FER171",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "sumicoat",
            unidad = "GRAMO",
            stockInicial = 20000.0,
            filasExcel = listOf(18),
        ),
        QuimicoCanonico(
            documentoId = "Q-U-FER005-BODEGA-AZUL",
            codigoOriginal = "U-FER005",
            categoria = "Fertilizante org\u00e1nico",
            subcategoria = "Org\u00e1nico / bioestimulante",
            ubicacion = "BODEGA AZUL",
            item = "ZING ORGANIC",
            unidad = "GRAMO",
            stockInicial = 3000.0,
            filasExcel = listOf(19),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER140-BODEGA-AZUL",
            codigoOriginal = "FER140",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "ACTIPHYL CRECIPHYL",
            unidad = "ML",
            stockInicial = 2780.0,
            filasExcel = listOf(20),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER124-BODEGA-AZUL",
            codigoOriginal = "FER124",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "ACTIPLANT",
            unidad = "ML",
            stockInicial = 14520.0,
            filasExcel = listOf(21),
        ),
        QuimicoCanonico(
            documentoId = "Q-FUN006-BODEGA-AZUL",
            codigoOriginal = "FUN006",
            categoria = "Fungicida",
            subcategoria = "Foliar sanitario",
            ubicacion = "BODEGA AZUL",
            item = "98 - AMISTAR TOP SC",
            unidad = "ML",
            stockInicial = 7678.0,
            filasExcel = listOf(22),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER058-BODEGA-AZUL",
            codigoOriginal = "FER058",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "90 - BORO FOLIAR - Microkel boro",
            unidad = "ML",
            stockInicial = 2550.0,
            filasExcel = listOf(23),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER059-BODEGA-AZUL",
            codigoOriginal = "FER059",
            categoria = "Acondicionador",
            subcategoria = "Acondicionador de mezcla",
            ubicacion = "BODEGA AZUL",
            item = "CALCIO FOLIAR - Smart Calcio",
            unidad = "ML",
            stockInicial = 6800.0,
            filasExcel = listOf(24),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR034-BODEGA-AZUL",
            codigoOriginal = "VAR034",
            categoria = "Coadyuvante",
            subcategoria = "Corrector de mezcla",
            ubicacion = "BODEGA AZUL",
            item = "CARRIER",
            unidad = "ML",
            stockInicial = 43000.0,
            filasExcel = listOf(25),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER169-BODEGA-AZUL",
            codigoOriginal = "FER169",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "90- ENGROSE X 20 LT",
            unidad = "ML",
            stockInicial = 100000.0,
            filasExcel = listOf(26),
        ),
        QuimicoCanonico(
            documentoId = "Q-INS005-BODEGA-AZUL",
            codigoOriginal = "INS005",
            categoria = "Insecticida",
            subcategoria = "Control de insectos",
            ubicacion = "BODEGA AZUL",
            item = "EXALT 60 SC",
            unidad = "ML",
            stockInicial = 35.0,
            filasExcel = listOf(27),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER145-BODEGA-AZUL",
            codigoOriginal = "FER145",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "82 - FERTIAMINO",
            unidad = "ML",
            stockInicial = 108389.0,
            filasExcel = listOf(28),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER147-BODEGA-AZUL",
            codigoOriginal = "FER147",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "82 - FERTIQUEL Mg",
            unidad = "ML",
            stockInicial = 28400.0,
            filasExcel = listOf(29),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR018-BODEGA-AZUL",
            codigoOriginal = "VAR018",
            categoria = "Coadyuvante",
            subcategoria = "Adherente / dispersante",
            ubicacion = "BODEGA AZUL",
            item = "FLUYEX",
            unidad = "ML",
            stockInicial = 575.0,
            filasExcel = listOf(30),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER016-BODEGA-AZUL",
            codigoOriginal = "FER016",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "82 - FOLCAMAG",
            unidad = "ML",
            stockInicial = 60000.0,
            filasExcel = listOf(31),
        ),
        QuimicoCanonico(
            documentoId = "Q-FUN024-BODEGA-AZUL",
            codigoOriginal = "FUN024",
            categoria = "Fungicida",
            subcategoria = "Suelo / vivero",
            ubicacion = "BODEGA AZUL",
            item = "funbacter",
            unidad = "ML",
            stockInicial = 1900.0,
            filasExcel = listOf(32),
        ),
        QuimicoCanonico(
            documentoId = "Q-INS009-BODEGA-AZUL",
            codigoOriginal = "INS009",
            categoria = "Insecticida",
            subcategoria = "Control de insectos",
            ubicacion = "BODEGA AZUL",
            item = "HAWKER PLUS",
            unidad = "ML",
            stockInicial = 60.0,
            filasExcel = listOf(33),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER125-BODEGA-AZUL",
            codigoOriginal = "FER125",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "INDUPLANT",
            unidad = "ML",
            stockInicial = 10000.0,
            filasExcel = listOf(34),
        ),
        QuimicoCanonico(
            documentoId = "Q-INS004-BODEGA-AZUL",
            codigoOriginal = "INS004",
            categoria = "Insecticida",
            subcategoria = "Insecticida / acaricida",
            ubicacion = "BODEGA AZUL",
            item = "KARATE ZEON 5%",
            unidad = "ML",
            stockInicial = 800.0,
            filasExcel = listOf(35),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER111-BODEGA-AZUL",
            codigoOriginal = "FER111",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "LUCTUS",
            unidad = "ML",
            stockInicial = 2000.0,
            filasExcel = listOf(36),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER105-BODEGA-AZUL",
            codigoOriginal = "FER105",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "Microckel Calcio Boro",
            unidad = "ML",
            stockInicial = 7000.0,
            filasExcel = listOf(37),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER144-BODEGA-AZUL",
            codigoOriginal = "FER144",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "82 - N300",
            unidad = "ML",
            stockInicial = 341900.0,
            filasExcel = listOf(38),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER015-BODEGA-AZUL",
            codigoOriginal = "FER015",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "98 - Nutriquel Menores x 1 litro",
            unidad = "ML",
            stockInicial = 6000.0,
            filasExcel = listOf(39),
        ),
        QuimicoCanonico(
            documentoId = "Q-FUN023-BODEGA-AZUL",
            codigoOriginal = "FUN023",
            categoria = "Fungicida",
            subcategoria = "Suelo / vivero",
            ubicacion = "BODEGA AZUL",
            item = "PREVALOR",
            unidad = "ML",
            stockInicial = 1400.0,
            filasExcel = listOf(40),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER143-BODEGA-AZUL",
            codigoOriginal = "FER143",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "82 - PRIMORDIAL PK",
            unidad = "ML",
            stockInicial = 204820.0,
            filasExcel = listOf(41),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR044-BODEGA-AZUL",
            codigoOriginal = "VAR044",
            categoria = "Regulador",
            subcategoria = "Regulador de crecimiento",
            ubicacion = "BODEGA AZUL",
            item = "90 - PROMALINA REGULADOR DE CRECIMIENTO",
            unidad = "ML",
            stockInicial = 500.0,
            filasExcel = listOf(42),
        ),
        QuimicoCanonico(
            documentoId = "Q-U-VAR002-BODEGA-AZUL",
            codigoOriginal = "U-VAR002",
            categoria = "Coadyuvante",
            subcategoria = "Adherente / dispersante",
            ubicacion = "BODEGA AZUL",
            item = "90 - SILICONEX",
            unidad = "ML",
            stockInicial = 6000.0,
            filasExcel = listOf(43),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER115-BODEGA-AZUL",
            codigoOriginal = "FER115",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Drench / fertirriego",
            ubicacion = "BODEGA AZUL",
            item = "STIMPLEX",
            unidad = "ML",
            stockInicial = 5000.0,
            filasExcel = listOf(44),
        ),
        QuimicoCanonico(
            documentoId = "Q-BIO018-BODEGA-AZUL",
            codigoOriginal = "BIO018",
            categoria = "Fungicida",
            subcategoria = "Suelo / vivero",
            ubicacion = "BODEGA AZUL",
            item = "TIMOREX GOLD",
            unidad = "ML",
            stockInicial = 2000.0,
            filasExcel = listOf(45),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR036-BODEGA-AZUL",
            codigoOriginal = "VAR036",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Nutrici\u00f3n general",
            ubicacion = "BODEGA AZUL",
            item = "TRANSFER ADHEX",
            unidad = "ML",
            stockInicial = 10800.0,
            filasExcel = listOf(46),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR028-BODEGA-AZUL",
            codigoOriginal = "VAR028",
            categoria = "Acondicionador",
            subcategoria = "Acondicionador de mezcla",
            ubicacion = "BODEGA AZUL",
            item = "TRANSFER IONIC",
            unidad = "ML",
            stockInicial = 3650.0,
            filasExcel = listOf(47),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER173-BODEGA-AZUL",
            codigoOriginal = "FER173",
            categoria = "Fertilizante org\u00e1nico",
            subcategoria = "Org\u00e1nico / bioestimulante",
            ubicacion = "BODEGA AZUL",
            item = "tropical algae",
            unidad = "ML",
            stockInicial = 2600.0,
            filasExcel = listOf(48),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER065-BODEGA-AZUL",
            codigoOriginal = "FER065",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Nutrici\u00f3n general",
            ubicacion = "BODEGA AZUL",
            item = "82 - VIOSURF PH Fertilizante",
            unidad = "ML",
            stockInicial = 17590.0,
            filasExcel = listOf(49),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER151-BODEGA-AZUL",
            codigoOriginal = "FER151",
            categoria = "Fungicida",
            subcategoria = "Suelo / vivero",
            ubicacion = "BODEGA AZUL",
            item = "YODOSAFER SL",
            unidad = "ML",
            stockInicial = 4400.0,
            filasExcel = listOf(50),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER060-BODEGA-AZUL",
            codigoOriginal = "FER060",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "ZIINC FOLIAR - Smart Zinc",
            unidad = "ML",
            stockInicial = 19270.0,
            filasExcel = listOf(51),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER142-BODEGA-AZUL",
            codigoOriginal = "FER142",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Foliar",
            ubicacion = "BODEGA AZUL",
            item = "82 - ZINCNERGIA",
            unidad = "ML",
            stockInicial = 121630.0,
            filasExcel = listOf(52),
        ),
        QuimicoCanonico(
            documentoId = "Q-VAR046-COP",
            codigoOriginal = "VAR046",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "90 -11-30-10 - PRECISAGRO",
            unidad = "GRAMO",
            stockInicial = 241000.0,
            filasExcel = listOf(53),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER038-COP",
            codigoOriginal = "FER038",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "FORCA MIX 10-30-10",
            unidad = "GRAMO",
            stockInicial = 225000.0,
            filasExcel = listOf(54),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER153-COP",
            codigoOriginal = "FER153",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "90 - BORO GRANULADO",
            unidad = "GRAMO",
            stockInicial = 35000.0,
            filasExcel = listOf(55),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER091-COP",
            codigoOriginal = "FER091",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "BOROZINPLANT",
            unidad = "GRAMO",
            stockInicial = 55000.0,
            filasExcel = listOf(56),
        ),
        QuimicoCanonico(
            documentoId = "Q-FEO014-COP",
            codigoOriginal = "FEO014",
            categoria = "Fertilizante org\u00e1nico",
            subcategoria = "Sustrato / compost",
            ubicacion = "COP",
            item = "82 - CARBOX COMPOST * 50 Kg",
            unidad = "GRAMO",
            stockInicial = 650000.0,
            filasExcel = listOf(57),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER055-COP",
            codigoOriginal = "FER055",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "CLORURO DE POTASIO",
            unidad = "GRAMO",
            stockInicial = 1305100.0,
            filasExcel = listOf(58),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER141-COP",
            codigoOriginal = "FER141",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "82 - COMPLEX",
            unidad = "GRAMO",
            stockInicial = 91000.0,
            filasExcel = listOf(59),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER163-COP",
            codigoOriginal = "FER163",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "90 - DAP GRANULADO",
            unidad = "GRAMO",
            stockInicial = 420000.0,
            filasExcel = listOf(60),
        ),
        QuimicoCanonico(
            documentoId = "Q-ENM014-COP",
            codigoOriginal = "ENM014",
            categoria = "Enmienda",
            subcategoria = "Fosfatos / correctivo",
            ubicacion = "COP",
            item = "82-FOSFORITA 24% HUILA MINEROS",
            unidad = "GRAMO",
            stockInicial = 2150000.0,
            filasExcel = listOf(61),
        ),
        QuimicoCanonico(
            documentoId = "Q-ENM016-COP",
            codigoOriginal = "ENM016",
            categoria = "Enmienda",
            subcategoria = "Fosfatos / correctivo",
            ubicacion = "COP",
            item = "FOSFORITA HUILA POLVO (Fosfatos)",
            unidad = "GRAMO",
            stockInicial = 2150000.0,
            filasExcel = listOf(62),
        ),
        QuimicoCanonico(
            documentoId = "Q-ENM012-COP",
            codigoOriginal = "ENM012",
            categoria = "Enmienda",
            subcategoria = "Correctivo de suelo",
            ubicacion = "COP",
            item = "Kalmag Hx",
            unidad = "GRAMO",
            stockInicial = 300000.0,
            filasExcel = listOf(63),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER033-COP",
            codigoOriginal = "FER033",
            categoria = "Fertilizante org\u00e1nico",
            subcategoria = "Biol\u00f3gico / inoculante",
            ubicacion = "COP",
            item = "MICORRIZA BULTO X KG",
            unidad = "GRAMO",
            stockInicial = 202000.0,
            filasExcel = listOf(64),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER068-COP",
            codigoOriginal = "FER068",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "82- NITRATO DE POTASIO - AMISOL",
            unidad = "GRAMO",
            stockInicial = 125000.0,
            filasExcel = listOf(65),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER158-COP",
            codigoOriginal = "FER158",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "82 -SULCAMAG *50KG",
            unidad = "GRAMO",
            stockInicial = 1070000.0,
            filasExcel = listOf(66),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER081-COP",
            codigoOriginal = "FER081",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "Sulfato de Amonio granulado x 50kg",
            unidad = "GRAMO",
            stockInicial = 139000.0,
            filasExcel = listOf(67),
        ),
        QuimicoCanonico(
            documentoId = "Q-BFE009-COP",
            codigoOriginal = "BFE009",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "90 - Sulfato de magnesio",
            unidad = "GRAMO",
            stockInicial = 173235.0,
            filasExcel = listOf(68),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER019-COP",
            codigoOriginal = "FER019",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "Sulfato de Zinc microfertisa (Solido)",
            unidad = "GRAMO",
            stockInicial = 161000.0,
            filasExcel = listOf(69),
        ),
        QuimicoCanonico(
            documentoId = "Q-U-BFE008-COP",
            codigoOriginal = "U-BFE008",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "90 - SULFEX COBRE",
            unidad = "GRAMO",
            stockInicial = 5000.0,
            filasExcel = listOf(70),
        ),
        QuimicoCanonico(
            documentoId = "Q-BFE012-COP",
            codigoOriginal = "BFE012",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "Sulfex Hierro",
            unidad = "GRAMO",
            stockInicial = 228000.0,
            filasExcel = listOf(71),
        ),
        QuimicoCanonico(
            documentoId = "Q-U-BFE006-COP",
            codigoOriginal = "U-BFE006",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "SULFEX MAGNESIO",
            unidad = "GRAMO",
            stockInicial = 180000.0,
            filasExcel = listOf(72),
        ),
        QuimicoCanonico(
            documentoId = "Q-BFE011-COP",
            codigoOriginal = "BFE011",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "Sulfex manganeso",
            unidad = "GRAMO",
            stockInicial = 378000.0,
            filasExcel = listOf(73),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER162-COP",
            codigoOriginal = "FER162",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "COP",
            item = "90 - UREA",
            unidad = "GRAMO",
            stockInicial = 345000.0,
            filasExcel = listOf(74, 75),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER098-PORTUGUESA",
            codigoOriginal = "FER098",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "ACIDO BORICO",
            unidad = "GRAMO",
            stockInicial = 304000.0,
            filasExcel = listOf(76),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER067-PORTUGUESA",
            codigoOriginal = "FER067",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "FOSFACID BORO ZINC",
            unidad = "GRAMO",
            stockInicial = 53000.0,
            filasExcel = listOf(77),
        ),
        QuimicoCanonico(
            documentoId = "Q-FEO014-PORTUGUESA",
            codigoOriginal = "FEO014",
            categoria = "Fertilizante org\u00e1nico",
            subcategoria = "Sustrato / compost",
            ubicacion = "PORTUGUESA",
            item = "82 - CARBOX COMPOST * 50 Kg",
            unidad = "GRAMO",
            stockInicial = 800000.0,
            filasExcel = listOf(78),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER077-PORTUGUESA",
            codigoOriginal = "FER077",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "Cloruro de Potasion cristales hidrosoluble estandar",
            unidad = "GRAMO",
            stockInicial = 325000.0,
            filasExcel = listOf(79),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER159-PORTUGUESA",
            codigoOriginal = "FER159",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "82 -FIRMEZA ORIGEN",
            unidad = "GRAMO",
            stockInicial = 1900000.0,
            filasExcel = listOf(80),
        ),
        QuimicoCanonico(
            documentoId = "Q-ENM014-PORTUGUESA",
            codigoOriginal = "ENM014",
            categoria = "Enmienda",
            subcategoria = "Fosfatos / correctivo",
            ubicacion = "PORTUGUESA",
            item = "82-FOSFORITA 24% HUILA MINEROS",
            unidad = "GRAMO",
            stockInicial = 6950000.0,
            filasExcel = listOf(81),
        ),
        QuimicoCanonico(
            documentoId = "Q-ENM002-PORTUGUESA",
            codigoOriginal = "ENM002",
            categoria = "Enmienda",
            subcategoria = "Fosfatos / correctivo",
            ubicacion = "PORTUGUESA",
            item = "90 - ROCA FOSFORICA",
            unidad = "GRAMO",
            stockInicial = 3400000.0,
            filasExcel = listOf(82),
        ),
        QuimicoCanonico(
            documentoId = "Q-ENM012-PORTUGUESA",
            codigoOriginal = "ENM012",
            categoria = "Enmienda",
            subcategoria = "Correctivo de suelo",
            ubicacion = "PORTUGUESA",
            item = "Kalmag Hx",
            unidad = "GRAMO",
            stockInicial = 900000.0,
            filasExcel = listOf(83),
        ),
        QuimicoCanonico(
            documentoId = "Q-FUN011-PORTUGUESA",
            codigoOriginal = "FUN011",
            categoria = "Fungicida",
            subcategoria = "Foliar sanitario",
            ubicacion = "PORTUGUESA",
            item = "NITRATO DE CALCIO",
            unidad = "GRAMO",
            stockInicial = 800000.0,
            filasExcel = listOf(84),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER150-PORTUGUESA",
            codigoOriginal = "FER150",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "RAFOS 12-24-12",
            unidad = "GRAMO",
            stockInicial = 200000.0,
            filasExcel = listOf(85),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER090-PORTUGUESA",
            codigoOriginal = "FER090",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "SILIPLANT Ca MG",
            unidad = "GRAMO",
            stockInicial = 50000.0,
            filasExcel = listOf(86),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER152-PORTUGUESA",
            codigoOriginal = "FER152",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "SULCAMAG * 50KG - SULCAMAG",
            unidad = "GRAMO",
            stockInicial = 1500000.0,
            filasExcel = listOf(87),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER081-PORTUGUESA",
            codigoOriginal = "FER081",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "Sulfato de Amonio granulado x 50kg",
            unidad = "GRAMO",
            stockInicial = 10000.0,
            filasExcel = listOf(88),
        ),
        QuimicoCanonico(
            documentoId = "Q-FER162-PORTUGUESA",
            codigoOriginal = "FER162",
            categoria = "Fertilizante qu\u00edmico",
            subcategoria = "Ed\u00e1fico / suelo",
            ubicacion = "PORTUGUESA",
            item = "90 - UREA",
            unidad = "GRAMO",
            stockInicial = 20000.0,
            filasExcel = listOf(89),
        ),
        QuimicoCanonico(
            documentoId = "Q-ENM017-PORTUGUESA",
            codigoOriginal = "ENM017",
            categoria = "Enmienda",
            subcategoria = "Correctivo de suelo",
            ubicacion = "PORTUGUESA",
            item = "YESO AGRICOLA EN POLVO",
            unidad = "GRAMO",
            stockInicial = 125000.0,
            filasExcel = listOf(90),
        ),
        QuimicoCanonico(
            documentoId = "Q-URE001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "URE001",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Urea automotriz",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "UREA AUTOMOTRIZ AUS 32 (5 GALONES)",
            unidad = "ML",
            stockInicial = 8000.0,
            filasExcel = listOf(91),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB006-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB006",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE GEAR OIL GL-5 80W-90 (5 GALONES)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(92),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB011-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB011",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "AXIS SAE 80W90 GL-5 (5 LITROS)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(93),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB005-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB005",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "LUBRICANTE STARMAX 80W90 (5 GALONES)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(94),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB001",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE TERPEL CELERITY 2T (1/4 GALON)",
            unidad = "UNIDAD",
            stockInicial = 8.0,
            filasExcel = listOf(95),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB004-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB004",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE MOBIL DELVAC 15W-40 (5 GALONES)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(96),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB007-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB007",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE MOBIL 424 (5 GALONES)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(97),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB002",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE MOBIL SUPER 2000 10W-30 (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(98),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB003-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB003",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE MOBIL SUPER 20W-50 4T (1/4 GALON)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(99),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB009-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB009",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE MULTIUSOS 3-EN-UNO 90ML",
            unidad = "UNIDAD",
            stockInicial = 1.0,
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB012-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB012",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aerosoles / multiusos",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ABRO AB80 (400 ML)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(100),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB010-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB010",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aerosoles / multiusos",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "WD-40 MULTIUSOS (382 ML)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(101),
        ),
        QuimicoCanonico(
            documentoId = "Q-LIM007-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LIM007",
            categoria = "Taller y mantenimiento",
            subcategoria = "Limpieza t\u00e9cnica",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "UNI-80 LUBRICANTE MULTIUSOS (400 ML)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(102),
        ),
        QuimicoCanonico(
            documentoId = "Q-ADI001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "ADI001",
            categoria = "Coadyuvante",
            subcategoria = "Corrector de mezcla",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACIDIFICANTE LIQUIDO CITROQUIM AQUA (5 GALONES)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(103),
        ),
        QuimicoCanonico(
            documentoId = "Q-ALC001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "ALC001",
            categoria = "Limpieza y desinfecci\u00f3n",
            subcategoria = "Alcoholes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ALCOHOL ANTISEPTICO (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(104),
        ),
        QuimicoCanonico(
            documentoId = "Q-DES002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "DES002",
            categoria = "Limpieza y desinfecci\u00f3n",
            subcategoria = "Clorados",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "CLORO (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(105),
        ),
        QuimicoCanonico(
            documentoId = "Q-DES003-CASETA-DE-LUBRICANTES",
            codigoOriginal = "DES003",
            categoria = "Limpieza y desinfecci\u00f3n",
            subcategoria = "Clorados",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "HIPOCLORITO (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(106),
        ),
        QuimicoCanonico(
            documentoId = "Q-FRE001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "FRE001",
            categoria = "Lubricantes y fluidos",
            subcategoria = "L\u00edquido de frenos",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "DOT-4 ISIN",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(107),
        ),
        QuimicoCanonico(
            documentoId = "Q-PIN002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "PIN002",
            categoria = "Taller y mantenimiento",
            subcategoria = "Limpieza t\u00e9cnica",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "EVERMAX VINILO PROFESIONAL (5 GALONES)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(108),
        ),
        QuimicoCanonico(
            documentoId = "Q-GRS001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "GRS001",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Grasas",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "GRASA LUBRICANTE AUPRO AZUL",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(109),
        ),
        QuimicoCanonico(
            documentoId = "Q-GRS002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "GRS002",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Grasas",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "GRASA MULTIBEG CHASIS GRADO 3",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(110),
        ),
        QuimicoCanonico(
            documentoId = "Q-LUB013-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LUB013",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Aceites",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "ACEITE SHINDAIWA ONE JASO-FS (1/4 GALON)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(111),
        ),
        QuimicoCanonico(
            documentoId = "Q-LIM008-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LIM008",
            categoria = "Taller y mantenimiento",
            subcategoria = "Limpieza t\u00e9cnica",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "PERFOMAX LIMPIA CONTACTO (250 ML)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(112),
        ),
        QuimicoCanonico(
            documentoId = "Q-LIM009-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LIM009",
            categoria = "Taller y mantenimiento",
            subcategoria = "Limpieza t\u00e9cnica",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "UDUKE LIMPIA CONTACTO",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(113),
        ),
        QuimicoCanonico(
            documentoId = "Q-LIM010-CASETA-DE-LUBRICANTES",
            codigoOriginal = "LIM010",
            categoria = "Taller y mantenimiento",
            subcategoria = "Limpieza t\u00e9cnica",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "LIMPIAMAX LIMPIADOR PAVCO",
            unidad = "UNIDAD",
            stockInicial = 4.0,
            filasExcel = listOf(114),
        ),
        QuimicoCanonico(
            documentoId = "Q-ADH001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "ADH001",
            categoria = "Taller y mantenimiento",
            subcategoria = "Adhesivos PVC",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "PAVCO SOLDAMAX (1/4 GALON)",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(115),
        ),
        QuimicoCanonico(
            documentoId = "Q-ADH002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "ADH002",
            categoria = "Taller y mantenimiento",
            subcategoria = "Adhesivos PVC",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "SOLDADURA LIQUIDA PVC",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(116),
        ),
        QuimicoCanonico(
            documentoId = "Q-ADH003-CASETA-DE-LUBRICANTES",
            codigoOriginal = "ADH003",
            categoria = "Taller y mantenimiento",
            subcategoria = "Adhesivos PVC",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "PAVCO SOLDAMAX (1/8 GALON)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(117),
        ),
        QuimicoCanonico(
            documentoId = "Q-REM001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "REM001",
            categoria = "Taller y mantenimiento",
            subcategoria = "Solventes / removedores",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "LIMPIADOR REMOVEDOR",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(118),
        ),
        QuimicoCanonico(
            documentoId = "Q-FRE002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "FRE002",
            categoria = "Lubricantes y fluidos",
            subcategoria = "L\u00edquido de frenos",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "LIQUIDO DE FRENOS",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(119),
        ),
        QuimicoCanonico(
            documentoId = "Q-MAS001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "MAS001",
            categoria = "Taller y mantenimiento",
            subcategoria = "Masillas / sellantes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "masilla poliester rosada poliescol",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(120),
        ),
        QuimicoCanonico(
            documentoId = "Q-PIN001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "PIN001",
            categoria = "Taller y mantenimiento",
            subcategoria = "Pinturas",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "PINTURA ASFALTICA PERMOVARETO BLACK (5 GALONES)",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(121),
        ),
        QuimicoCanonico(
            documentoId = "Q-REF001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "REF001",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Refrigerantes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "MAG1 REFRIGERANTE ANTICORROSIVO (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(122),
        ),
        QuimicoCanonico(
            documentoId = "Q-REF002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "REF002",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Refrigerantes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "REFRIGERANTE TERPEL PARA RADIADORES ESTANDAR (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(123),
        ),
        QuimicoCanonico(
            documentoId = "Q-REF003-CASETA-DE-LUBRICANTES",
            codigoOriginal = "REF003",
            categoria = "Lubricantes y fluidos",
            subcategoria = "Refrigerantes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "REFRIGERANTE VELKOOLANT (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 6.0,
            filasExcel = listOf(124),
        ),
        QuimicoCanonico(
            documentoId = "Q-REM002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "REM002",
            categoria = "Taller y mantenimiento",
            subcategoria = "Solventes / removedores",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "REMOVEDOR DE ESMALTE",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(125),
        ),
        QuimicoCanonico(
            documentoId = "Q-SOL002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "SOL002",
            categoria = "Taller y mantenimiento",
            subcategoria = "Solventes / removedores",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "THINNER (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(126),
        ),
        QuimicoCanonico(
            documentoId = "Q-SOL001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "SOL001",
            categoria = "Taller y mantenimiento",
            subcategoria = "Solventes / removedores",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "VARSOL (1 GALON)",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(127),
        ),
        QuimicoCanonico(
            documentoId = "Q-SEL001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "SEL001",
            categoria = "Taller y mantenimiento",
            subcategoria = "Masillas / sellantes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "SUPERMASTICK PR",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(128),
        ),
        QuimicoCanonico(
            documentoId = "Q-VUL001-CASETA-DE-LUBRICANTES",
            codigoOriginal = "VUL001",
            categoria = "Taller y mantenimiento",
            subcategoria = "Vulcanizantes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "SOLUCION VULCANIZANTE CENTAURO",
            unidad = "UNIDAD",
            stockInicial = 3.0,
            filasExcel = listOf(129),
        ),
        QuimicoCanonico(
            documentoId = "Q-VUL002-CASETA-DE-LUBRICANTES",
            codigoOriginal = "VUL002",
            categoria = "Taller y mantenimiento",
            subcategoria = "Vulcanizantes",
            ubicacion = "CASETA DE LUBRICANTES",
            item = "VULCANIZANTE VIPAL",
            unidad = "UNIDAD",
            stockInicial = 2.0,
            filasExcel = listOf(130),
        ),
        QuimicoCanonico(
            documentoId = "Q-LAB001-OFICINA",
            codigoOriginal = "LAB001",
            categoria = "Laboratorio",
            subcategoria = "Soluciones pH / limpieza",
            ubicacion = "OFICINA",
            item = "HANNA INSTRUMENTS CLEANING (500 ML)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(131),
        ),
        QuimicoCanonico(
            documentoId = "Q-LAB002-OFICINA",
            codigoOriginal = "LAB002",
            categoria = "Laboratorio",
            subcategoria = "Soluciones pH / limpieza",
            ubicacion = "OFICINA",
            item = "HANNA INSTRUMENTS PH 4.01 (500 ML)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(132),
        ),
        QuimicoCanonico(
            documentoId = "Q-LAB003-OFICINA",
            codigoOriginal = "LAB003",
            categoria = "Laboratorio",
            subcategoria = "Soluciones pH / limpieza",
            ubicacion = "OFICINA",
            item = "HANNA INSTRUMENTS PH 7.01 (500 ML)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(133),
        ),
        QuimicoCanonico(
            documentoId = "Q-LAB004-OFICINA",
            codigoOriginal = "LAB004",
            categoria = "Laboratorio",
            subcategoria = "Soluciones pH / limpieza",
            ubicacion = "OFICINA",
            item = "HANNA INSTRUMENTS STORAGE (500 ML)",
            unidad = "UNIDAD",
            stockInicial = 1.0,
            filasExcel = listOf(134),
        ),
    )

    private fun norm(value: String): String = value.trim().uppercase(Locale.getDefault())

    fun agregarAlCatalogo(catalogo: MutableMap<String, MutableMap<String, MutableMap<String, MutableList<String>>>>) {
        items.forEach { producto ->
            val moduloMap = catalogo.getOrPut(producto.modulo) { mutableMapOf() }
            val categoriaMap = moduloMap.getOrPut(producto.categoria) { mutableMapOf() }
            val listaItems = categoriaMap.getOrPut(producto.subcategoria) { mutableListOf() }
            if (!listaItems.contains(producto.item)) listaItems.add(producto.item)
        }
    }

    fun buscar(categoria: String, subcategoria: String, item: String): QuimicoCanonico? {
        val cat = norm(categoria)
        val sub = norm(subcategoria)
        val itemNorm = norm(item)
        return items.firstOrNull { norm(it.categoria) == cat && norm(it.subcategoria) == sub && norm(it.item) == itemNorm }
    }

    fun buscar(modulo: String, categoria: String, subcategoria: String, item: String): QuimicoCanonico? {
        val mod = norm(modulo)
        val cat = norm(categoria)
        val sub = norm(subcategoria)
        val itemNorm = norm(item)
        return items.firstOrNull {
            norm(it.modulo) == mod && norm(it.categoria) == cat && norm(it.subcategoria) == sub && norm(it.item) == itemNorm
        } ?: buscar(categoria, subcategoria, item)
    }

    fun buscarPorDocumento(documentoId: String): QuimicoCanonico? {
        val id = norm(documentoId)
        return items.firstOrNull { norm(it.documentoId) == id }
    }

    fun buscarPorCodigoUbicacion(codigo: String, ubicacion: String, item: String = ""): QuimicoCanonico? {
        val cod = norm(codigo)
        val ubi = norm(ubicacion)
        val itemNorm = norm(item)
        return items.firstOrNull {
            norm(it.codigoOriginal) == cod && norm(it.ubicacion) == ubi && (itemNorm.isBlank() || norm(it.item) == itemNorm)
        }
    }

    fun ubicaciones(codigo: String, item: String = ""): List<QuimicoCanonico> {
        val cod = norm(codigo)
        val itemNorm = norm(item)
        return items.filter { norm(it.codigoOriginal) == cod && (itemNorm.isBlank() || norm(it.item) == itemNorm) }
    }

    fun totalInicial(codigo: String, item: String = ""): Double = ubicaciones(codigo, item).sumOf { it.stockInicial }

    fun esDocumentoCanonico(documentoId: String): Boolean = buscarPorDocumento(documentoId) != null

    fun esCodigoCanonico(codigo: String): Boolean {
        val cod = norm(codigo)
        return items.any { norm(it.codigoOriginal) == cod || norm(it.documentoId) == cod }
    }

    const val UBICACION_BODEGA_AZUL = "BODEGA AZUL"
    const val UBICACION_COP = "COP"
    const val UBICACION_PORTUGUESA = "PORTUGUESA"

    val UBICACIONES_AGROQUIMICOS = listOf(
        UBICACION_BODEGA_AZUL,
        UBICACION_COP,
        UBICACION_PORTUGUESA,
    )

    fun etiquetaTabUbicacion(ubicacion: String): String = when (norm(ubicacion)) {
        "TODOS" -> "Todos"
        UBICACION_BODEGA_AZUL -> "Bodega azul"
        UBICACION_COP -> "COP"
        UBICACION_PORTUGUESA -> "Portuguesa"
        else -> ubicacion
    }

    fun normalizarUbicacionAgroquimico(raw: String): String {
        val limpio = norm(raw)
        if (limpio.isBlank()) return ""
        return when {
            limpio == UBICACION_BODEGA_AZUL || (limpio.contains("BODEGA") && limpio.contains("AZUL")) -> UBICACION_BODEGA_AZUL
            limpio == UBICACION_COP -> UBICACION_COP
            limpio.contains("PORTUGUESA") -> UBICACION_PORTUGUESA
            else -> ""
        }
    }

    fun coincideUbicacionAgroquimico(itemUbicacion: String, filtro: String): Boolean {
        if (filtro.isBlank() || norm(filtro) == "TODOS") return true
        val filtroNormalizado = normalizarUbicacionAgroquimico(filtro)
        if (filtroNormalizado.isBlank()) return true
        return normalizarUbicacionAgroquimico(itemUbicacion) == filtroNormalizado
    }
}

